<a href="https://colab.research.google.com/github/koojaekwan/Kaggle_study/blob/master/Numpy_exercise2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy exercise 100  

* Refer - https://www.kaggle.com/python10pm/learn-numpy-the-hard-way-70-exercises-solutions



In [1]:
import os
import numpy as np
import pandas as pd
from sklearn import datasets
from scipy import stats

from google.colab import drive

drive.mount('./MyDrive')

Mounted at ./MyDrive


In [2]:
os.chdir('/content/MyDrive/MyDrive')  # setwd like R
os.getcwd()   # current working directory

'/content/MyDrive/MyDrive'

In [3]:
# Allow several prints in one cell
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# importing the core library
import numpy as np

# helper functions to list the datasets available
def print_files():
    import os
    for dirname, _, filenames in os.walk('/content/MyDrive/MyDrive'):
        for filename in filenames:
            print(os.path.join(dirname, filename))

print_files()

/content/MyDrive/MyDrive/train.csv
/content/MyDrive/MyDrive/test.csv
/content/MyDrive/MyDrive/머신러닝 도감(제이펍).gdoc
/content/MyDrive/MyDrive/srr-mave-gqc - 2020년 10월 11일.gjam
/content/MyDrive/MyDrive/trick99data.csv
/content/MyDrive/MyDrive/trick83data.csv
/content/MyDrive/MyDrive/trick78data1.csv
/content/MyDrive/MyDrive/trick78data3.csv
/content/MyDrive/MyDrive/trick78data2.csv
/content/MyDrive/MyDrive/trick58data.csv
/content/MyDrive/MyDrive/trick18data.csv.zip
/content/MyDrive/MyDrive/trick8data3.csv
/content/MyDrive/MyDrive/trick8data1.csv
/content/MyDrive/MyDrive/trick8data2.csv
/content/MyDrive/MyDrive/iris_new.csv
/content/MyDrive/MyDrive/coding_test/group_call_HMS.csv
/content/MyDrive/MyDrive/coding_test/first.pickle
/content/MyDrive/MyDrive/coding_test/first2.pickle
/content/MyDrive/MyDrive/coding_test/first3.pickle
/content/MyDrive/MyDrive/coding_test/first4.pickle
/content/MyDrive/MyDrive/coding_test/first5.pickle
/content/MyDrive/MyDrive/coding_test/p_data.p

In [4]:
with os.scandir('/content/MyDrive/MyDrive') as k: # 현재 폴더 내의 파일들(하위폴더 제외)
    for i in k:
        print(i)

<DirEntry 'train.csv'>
<DirEntry 'test.csv'>
<DirEntry '머신러닝 도감(제이펍).gdoc'>
<DirEntry 'coding_test'>
<DirEntry 'Colab Notebooks'>
<DirEntry 'srr-mave-gqc - 2020년 10월 11일.gjam'>
<DirEntry 'trick99data.csv'>
<DirEntry 'trick83data.csv'>
<DirEntry 'trick78data1.csv'>
<DirEntry 'trick78data3.csv'>
<DirEntry 'trick78data2.csv'>
<DirEntry 'trick58data.csv'>
<DirEntry 'trick18data.csv.zip'>
<DirEntry 'trick8data3.csv'>
<DirEntry 'trick8data1.csv'>
<DirEntry 'trick8data2.csv'>
<DirEntry 'archive.ics.uci.edu'>
<DirEntry 'iris_new.csv'>


In [5]:
os.listdir('/content/MyDrive/MyDrive')
# os.scandir('/content/MyDrive/MyDrive')

['train.csv',
 'test.csv',
 '머신러닝 도감(제이펍).gdoc',
 'coding_test',
 'Colab Notebooks',
 'srr-mave-gqc - 2020년 10월 11일.gjam',
 'trick99data.csv',
 'trick83data.csv',
 'trick78data1.csv',
 'trick78data3.csv',
 'trick78data2.csv',
 'trick58data.csv',
 'trick18data.csv.zip',
 'trick8data3.csv',
 'trick8data1.csv',
 'trick8data2.csv',
 'archive.ics.uci.edu',
 'iris_new.csv']

In [6]:
# os.walk 모든 파일/폴더 출력하기

workDIr = os.path.abspath('/content/MyDrive/MyDrive')
for dirpath, dirnames, filenames in os.walk(workDIr):
    print(dirpath)

    for dirname in dirnames:
        print("\t", dirname)

    for filename in filenames:
        print("\t", filename)

/content/MyDrive/MyDrive
	 coding_test
	 Colab Notebooks
	 archive.ics.uci.edu
	 train.csv
	 test.csv
	 머신러닝 도감(제이펍).gdoc
	 srr-mave-gqc - 2020년 10월 11일.gjam
	 trick99data.csv
	 trick83data.csv
	 trick78data1.csv
	 trick78data3.csv
	 trick78data2.csv
	 trick58data.csv
	 trick18data.csv.zip
	 trick8data3.csv
	 trick8data1.csv
	 trick8data2.csv
	 iris_new.csv
/content/MyDrive/MyDrive/coding_test
	 .ipynb_checkpoints
	 group_call_HMS.csv
	 first.pickle
	 first2.pickle
	 first3.pickle
	 first4.pickle
	 first5.pickle
	 p_data.pickle
	 final_dat.pickle
/content/MyDrive/MyDrive/coding_test/.ipynb_checkpoints
/content/MyDrive/MyDrive/Colab Notebooks
	 jaekwankoo.ipynb
	 chap1.ipynb
	 chap2 기본 자료구조와 배열.ipynb
	 recursive_function.ipynb
	 pandas_exercise1.ipynb
	 pandas_exercise2.ipynb
	 pandas_exercise3.ipynb
	 pandas_exercise4.ipynb
	 pandas_exercise5.ipynb
	 pandas_exercise6.ipynb
	 Untitled
	 Numpy_exercise2 (1).ipynb
	 Numpy_exercise1.ipynb
	 Numpy_exercise2.ipy

In [7]:
iris = datasets.load_iris()
df = pd.DataFrame(data = iris.data, columns = iris.feature_names)

df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [8]:
pd.DataFrame(iris.target).head()

0
0  0
1  0
2  0
3  0
4  0

In [9]:
df['target'] = pd.DataFrame(iris.target)[0].map({0:'setosa',1:'versicolor',2:'virginica'})
df

sepal length (cm)  sepal width (cm)  ...  petal width (cm)     target
0                  5.1               3.5  ...               0.2     setosa
1                  4.9               3.0  ...               0.2     setosa
2                  4.7               3.2  ...               0.2     setosa
3                  4.6               3.1  ...               0.2     setosa
4                  5.0               3.6  ...               0.2     setosa
..                 ...               ...  ...               ...        ...
145                6.7               3.0  ...               2.3  virginica
146                6.3               2.5  ...               1.9  virginica
147                6.5               3.0  ...               2.0  virginica
148                6.2               3.4  ...               2.3  virginica
149                5.9               3.0  ...               1.8  virginica

[150 rows x 5 columns]

In [10]:
df.to_csv('iris_new.csv')

In [11]:
# usecols=[0]은 index를 말함
iris = np.genfromtxt('iris_new.csv', delimiter=',',skip_header=1,usecols=[5],dtype='str') 
iris

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolo

In [12]:
df.target.values # series to array / 현재는 values method는 지양
df.target.to_numpy # to_numpy or array사용을 권장
df.target.array

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolo

<bound method IndexOpsMixin.to_numpy of 0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: target, Length: 150, dtype: object>

<PandasArray>
[   'setosa',    'setosa',    'setosa',    'setosa',    'setosa',    'setosa',
    'setosa',    'setosa',    'setosa',    'setosa',
 ...
 'virginica', 'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
 'virginica', 'virginica', 'virginica', 'virginica']
Length: 150, dtype: object

## 26. How to extract a particular column from 1D array of tuples?  

바이트 : https://dojang.io/mod/page/view.php?id=2462

In [13]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)

pd.DataFrame(iris_1d)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  


f0   f1   f2   f3                 f4
0    5.1  3.5  1.4  0.2     b'Iris-setosa'
1    4.9  3.0  1.4  0.2     b'Iris-setosa'
2    4.7  3.2  1.3  0.2     b'Iris-setosa'
3    4.6  3.1  1.5  0.2     b'Iris-setosa'
4    5.0  3.6  1.4  0.2     b'Iris-setosa'
..   ...  ...  ...  ...                ...
145  6.7  3.0  5.2  2.3  b'Iris-virginica'
146  6.3  2.5  5.0  1.9  b'Iris-virginica'
147  6.5  3.0  5.2  2.0  b'Iris-virginica'
148  6.2  3.4  5.4  2.3  b'Iris-virginica'
149  5.9  3.0  5.1  1.8  b'Iris-virginica'

[150 rows x 5 columns]

In [14]:
print("Solution")
iris = np.genfromtxt('iris_new.csv', delimiter=',', skip_header=1, usecols = [5], dtype='str')
iris[:4]

Solution


array(['setosa', 'setosa', 'setosa', 'setosa'], dtype='<U10')

In [15]:
# Solution from the website
print("Solution from website")

iris_1d = np.genfromtxt('iris_new.csv', delimiter=',', dtype=None)
species = np.array([row[5] for row in iris_1d])
species

Solution from website


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  after removing the cwd from sys.path.


array([b'target', b'setosa', b'setosa', b'setosa', b'setosa', b'setosa',
       b'setosa', b'setosa', b'setosa', b'setosa', b'setosa', b'setosa',
       b'setosa', b'setosa', b'setosa', b'setosa', b'setosa', b'setosa',
       b'setosa', b'setosa', b'setosa', b'setosa', b'setosa', b'setosa',
       b'setosa', b'setosa', b'setosa', b'setosa', b'setosa', b'setosa',
       b'setosa', b'setosa', b'setosa', b'setosa', b'setosa', b'setosa',
       b'setosa', b'setosa', b'setosa', b'setosa', b'setosa', b'setosa',
       b'setosa', b'setosa', b'setosa', b'setosa', b'setosa', b'setosa',
       b'setosa', b'setosa', b'setosa', b'versicolor', b'versicolor',
       b'versicolor', b'versicolor', b'versicolor', b'versicolor',
       b'versicolor', b'versicolor', b'versicolor', b'versicolor',
       b'versicolor', b'versicolor', b'versicolor', b'versicolor',
       b'versicolor', b'versicolor', b'versicolor', b'versicolor',
       b'versicolor', b'versicolor', b'versicolor', b'versicolor',
       b've

## 27. How to convert a 1d array of tuples to a 2d numpy array?

In [16]:
# Solution
iris = np.genfromtxt('iris_new.csv', delimiter=',', skip_header=1, 
                     usecols = [0, 1, 2, 3, 4], dtype = None)
iris[:8]

array([(0, 5.1, 3.5, 1.4, 0.2), (1, 4.9, 3. , 1.4, 0.2),
       (2, 4.7, 3.2, 1.3, 0.2), (3, 4.6, 3.1, 1.5, 0.2),
       (4, 5. , 3.6, 1.4, 0.2), (5, 5.4, 3.9, 1.7, 0.4),
       (6, 4.6, 3.4, 1.4, 0.3), (7, 5. , 3.4, 1.5, 0.2)],
      dtype=[('f0', '<i8'), ('f1', '<f8'), ('f2', '<f8'), ('f3', '<f8'), ('f4', '<f8')])

In [17]:
# Another solution from the website
iris_1d = np.genfromtxt('iris_new.csv', delimiter=',', dtype=None)
iris_2d = np.array([row.tolist()[:4] for row in iris_1d])
iris_2d[:4]

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  


array([[b'-1', b'sepal length (cm)', b'sepal width (cm)',
        b'petal length (cm)'],
       [b'0', b'5.1', b'3.5', b'1.4'],
       [b'1', b'4.9', b'3.0', b'1.4'],
       [b'2', b'4.7', b'3.2', b'1.3']], dtype='|S21')

In [18]:
[row for row in iris_1d][:4]

[(-1, b'sepal length (cm)', b'sepal width (cm)', b'petal length (cm)', b'petal width (cm)', b'target'),
 (0, b'5.1', b'3.5', b'1.4', b'0.2', b'setosa'),
 (1, b'4.9', b'3.0', b'1.4', b'0.2', b'setosa'),
 (2, b'4.7', b'3.2', b'1.3', b'0.2', b'setosa')]

In [19]:
[row.tolist() for row in iris_1d][:4]

[(-1,
  b'sepal length (cm)',
  b'sepal width (cm)',
  b'petal length (cm)',
  b'petal width (cm)',
  b'target'),
 (0, b'5.1', b'3.5', b'1.4', b'0.2', b'setosa'),
 (1, b'4.9', b'3.0', b'1.4', b'0.2', b'setosa'),
 (2, b'4.7', b'3.2', b'1.3', b'0.2', b'setosa')]

In [20]:
[row.tolist()[:5] for row in iris_1d][:4]

[(-1,
  b'sepal length (cm)',
  b'sepal width (cm)',
  b'petal length (cm)',
  b'petal width (cm)'),
 (0, b'5.1', b'3.5', b'1.4', b'0.2'),
 (1, b'4.9', b'3.0', b'1.4', b'0.2'),
 (2, b'4.7', b'3.2', b'1.3', b'0.2')]

In [21]:
np.array([row.tolist()[:5] for row in iris_1d][:4])

array([[b'-1', b'sepal length (cm)', b'sepal width (cm)',
        b'petal length (cm)', b'petal width (cm)'],
       [b'0', b'5.1', b'3.5', b'1.4', b'0.2'],
       [b'1', b'4.9', b'3.0', b'1.4', b'0.2'],
       [b'2', b'4.7', b'3.2', b'1.3', b'0.2']], dtype='|S21')

## 28. How to compute the mean, median, standard deviation of a numpy array?

In [22]:
# Q. Find the mean, median, standard deviation of iris's sepallength (1st column)

# Solution
print("Solution")
iris = np.genfromtxt('iris_new.csv', delimiter=',', skip_header=1, usecols = [1])
iris

Solution


array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])

In [23]:
pd.Series(iris).describe()

count    150.000000
mean       5.843333
std        0.828066
min        4.300000
25%        5.100000
50%        5.800000
75%        6.400000
max        7.900000
dtype: float64

In [24]:
stats.describe(iris)

DescribeResult(nobs=150, minmax=(4.3, 7.9), mean=5.843333333333334, variance=0.6856935123042507, skewness=0.3117530585022963, kurtosis=-0.5735679489249765)

In [25]:
# Solution from the website
print("Another solution from the website")

mu, med, sd = np.mean(iris), np.median(iris), np.std(iris)

print(mu, med, sd)

Another solution from the website
5.843333333333334 5.8 0.8253012917851409


## 29. How to normalize an array so the values range exactly between 0 and 1?

In [26]:
# Q. Create a normalized form of iris's sepallength whose values range exactly between 0 and 1 
#so that the minimum has value 0 and maximum has value 1.

# Solution
iris = np.genfromtxt("iris_new.csv", delimiter = ",", skip_header = 1, usecols = [1])

(iris - np.min(iris)) / (np.max(iris) - np.min(iris))

array([0.22222222, 0.16666667, 0.11111111, 0.08333333, 0.19444444,
       0.30555556, 0.08333333, 0.19444444, 0.02777778, 0.16666667,
       0.30555556, 0.13888889, 0.13888889, 0.        , 0.41666667,
       0.38888889, 0.30555556, 0.22222222, 0.38888889, 0.22222222,
       0.30555556, 0.22222222, 0.08333333, 0.22222222, 0.13888889,
       0.19444444, 0.19444444, 0.25      , 0.25      , 0.11111111,
       0.13888889, 0.30555556, 0.25      , 0.33333333, 0.16666667,
       0.19444444, 0.33333333, 0.16666667, 0.02777778, 0.22222222,
       0.19444444, 0.05555556, 0.02777778, 0.19444444, 0.22222222,
       0.13888889, 0.22222222, 0.08333333, 0.27777778, 0.19444444,
       0.75      , 0.58333333, 0.72222222, 0.33333333, 0.61111111,
       0.38888889, 0.55555556, 0.16666667, 0.63888889, 0.25      ,
       0.19444444, 0.44444444, 0.47222222, 0.5       , 0.36111111,
       0.66666667, 0.36111111, 0.41666667, 0.52777778, 0.36111111,
       0.44444444, 0.5       , 0.55555556, 0.5       , 0.58333

## 30. How to compute the softmax score?

In [27]:
# Q. Compute the softmax score of sepallength.

# Solution
# The Softmax regression is a form of logistic regression 
#that normalizes an input value into a vector of values 
#that follows a probability distribution whose total sums up to 1. 

iris = np.genfromtxt('iris_new.csv', delimiter=',', skip_header=1, usecols = [1])

softmax = np.exp(iris)/sum(np.exp(iris))
softmax

array([0.00221959, 0.00181724, 0.00148783, 0.00134625, 0.00200836,
       0.00299613, 0.00134625, 0.00200836, 0.00110221, 0.00181724,
       0.00299613, 0.00164431, 0.00164431, 0.00099732, 0.0044697 ,
       0.00404435, 0.00299613, 0.00221959, 0.00404435, 0.00221959,
       0.00299613, 0.00221959, 0.00134625, 0.00221959, 0.00164431,
       0.00200836, 0.00200836, 0.00245302, 0.00245302, 0.00148783,
       0.00164431, 0.00299613, 0.00245302, 0.00331123, 0.00181724,
       0.00200836, 0.00331123, 0.00181724, 0.00110221, 0.00221959,
       0.00200836, 0.00121813, 0.00110221, 0.00200836, 0.00221959,
       0.00164431, 0.00221959, 0.00134625, 0.00271101, 0.00200836,
       0.01483991, 0.00814432, 0.01342771, 0.00331123, 0.00900086,
       0.00404435, 0.00736928, 0.00181724, 0.00994749, 0.00245302,
       0.00200836, 0.00493978, 0.0054593 , 0.00603346, 0.00365948,
       0.01099368, 0.00365948, 0.0044697 , 0.006668  , 0.00365948,
       0.00493978, 0.00603346, 0.00736928, 0.00603346, 0.00814

In [28]:
# it must sum 1
softmax.sum()
sum(softmax)
np.sum(softmax)

0.9999999999999997

0.9999999999999997

0.9999999999999997

In [29]:
# We can also apply this to more than 1 column.
iris = np.genfromtxt('iris_new.csv', delimiter=',', skip_header=1, usecols = [1, 2, 3, 4])
softmax = np.exp(iris)/sum(np.exp(iris))

softmax.sum() # We have 4 since we have 4 columns, each sums 1
softmax

4.0

array([[0.00221959, 0.00940198, 0.00021035, 0.0018806 ],
       [0.00181724, 0.00570259, 0.00021035, 0.0018806 ],
       [0.00148783, 0.00696516, 0.00019033, 0.0018806 ],
       [0.00134625, 0.00630234, 0.00023247, 0.0018806 ],
       [0.00200836, 0.0103908 , 0.00021035, 0.0018806 ],
       [0.00299613, 0.01402611, 0.00028394, 0.00229697],
       [0.00134625, 0.00850727, 0.00021035, 0.00207838],
       [0.00200836, 0.00850727, 0.00023247, 0.0018806 ],
       [0.00110221, 0.00515992, 0.00021035, 0.0018806 ],
       [0.00181724, 0.00630234, 0.00023247, 0.00170164],
       [0.00299613, 0.01148361, 0.00023247, 0.0018806 ],
       [0.00164431, 0.00850727, 0.00025692, 0.0018806 ],
       [0.00164431, 0.00570259, 0.00021035, 0.00170164],
       [0.00099732, 0.00570259, 0.00015583, 0.00170164],
       [0.0044697 , 0.01550125, 0.00017222, 0.0018806 ],
       [0.00404435, 0.02312514, 0.00023247, 0.00229697],
       [0.00299613, 0.01402611, 0.00019033, 0.00229697],
       [0.00221959, 0.00940198,

In [30]:
# Solution from the website
print("Solution from the website")

def softmax(x):
    """Compute softmax values for each sets of scores in x.
    https://stackoverflow.com/questions/34968722/how-to-implement-the-softmax-function-in-python"""
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum(axis=0) # columns

print(softmax(iris).sum())
print(softmax(iris))

Solution from the website
4.0
[[0.00221959 0.00940198 0.00021035 0.0018806 ]
 [0.00181724 0.00570259 0.00021035 0.0018806 ]
 [0.00148783 0.00696516 0.00019033 0.0018806 ]
 [0.00134625 0.00630234 0.00023247 0.0018806 ]
 [0.00200836 0.0103908  0.00021035 0.0018806 ]
 [0.00299613 0.01402611 0.00028394 0.00229697]
 [0.00134625 0.00850727 0.00021035 0.00207838]
 [0.00200836 0.00850727 0.00023247 0.0018806 ]
 [0.00110221 0.00515992 0.00021035 0.0018806 ]
 [0.00181724 0.00630234 0.00023247 0.00170164]
 [0.00299613 0.01148361 0.00023247 0.0018806 ]
 [0.00164431 0.00850727 0.00025692 0.0018806 ]
 [0.00164431 0.00570259 0.00021035 0.00170164]
 [0.00099732 0.00570259 0.00015583 0.00170164]
 [0.0044697  0.01550125 0.00017222 0.0018806 ]
 [0.00404435 0.02312514 0.00023247 0.00229697]
 [0.00299613 0.01402611 0.00019033 0.00229697]
 [0.00221959 0.00940198 0.00021035 0.00207838]
 [0.00404435 0.01269135 0.00028394 0.00207838]
 [0.00221959 0.01269135 0.00023247 0.00207838]
 [0.00299613 0.00850727 0.0002

In [31]:
pd.DataFrame(iris)[0]

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ... 
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: 0, Length: 150, dtype: float64

In [32]:
softmax(pd.DataFrame(iris)[0])

0      0.002220
1      0.001817
2      0.001488
3      0.001346
4      0.002008
         ...   
145    0.010994
146    0.007369
147    0.009001
148    0.006668
149    0.004940
Name: 0, Length: 150, dtype: float64

In [33]:
softmax(pd.DataFrame(iris)[0]).sum(axis = 0)

1.0000000000000002

## 31. How to find the percentile scores of a numpy array?

In [34]:
# Q. Find the 5th and 95th percentile of iris's sepallength

# Solution
iris = np.genfromtxt('iris_new.csv', delimiter=',', skip_header=1, usecols = [1])

iris

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])

In [35]:
np.percentile(iris, q = [5, 95])

array([4.6  , 7.255])

## 32. How to insert values at random positions in an array?

In [36]:
# Q. Insert np.nan values at 20 random positions in iris_2d dataset

# Solution
iris = np.genfromtxt('iris_new.csv', delimiter=',', skip_header=1, usecols = [1, 2, 3, 4])
index = np.random.randint(0, 150, 20)

index

array([ 27,  67, 137, 129,  56,  12, 141, 131, 112, 113,  56,   8,  14,
       141,  67,  83, 107,  58,  36,  76])

In [37]:
iris[index] = np.nan

iris

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [nan, nan, nan, nan],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [nan, nan, nan, nan],
       [4.3, 3. , 1.1, 0.1],
       [nan, nan, nan, nan],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [nan, nan, nan, nan],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [38]:
# Solution from the website
print("Another solution from the website")

iris = np.genfromtxt('iris_new.csv', delimiter=',', skip_header=1, usecols = [1, 2, 3, 4])

# 행 열 위치를 반환
i, j = np.where(iris) # get the index of all 600 elements of the array

# i,j에 대해 랜덤하게 20개 nan위치를 생성
nan_index = [np.random.choice((i), 20), np.random.choice((j), 20)] # get some random values for each row and column

nan_index

Another solution from the website


[array([125,  58,  30, 126,  62,  63,  42, 102,  51,  30, 127, 137,  92,
          8,  72, 115,  28,  28, 117, 128]),
 array([1, 3, 2, 3, 0, 1, 1, 0, 2, 0, 2, 3, 2, 0, 2, 2, 0, 3, 1, 2])]

In [39]:
iris[nan_index] = np.nan
iris

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  """Entry point for launching an IPython kernel.


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [nan, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [nan, 3.4, 1.4, nan],
       [4.7, 3.2, 1.6, 0.2],
       [nan, 3.1, nan, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [40]:
# Solution 3 from the website
print("Solution 3 from the website")

iris = np.genfromtxt('iris_new.csv', delimiter=',', skip_header=1, usecols = [1, 2, 3, 4])
iris[np.random.randint(149, size=20), np.random.randint(4, size=20)] = np.nan
iris

Solution 3 from the website


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [nan, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , nan, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , nan, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [nan, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

## 33. How to find the position of missing values in numpy array?

In [41]:
#### Q. Find the number and position of missing values in iris_2d's sepallength (1st column)

# Solution
iris = np.genfromtxt('iris_new.csv', delimiter=',', skip_header=1, usecols = [1, 2, 3, 4])
iris[:,0][np.random.randint(0 , len(iris), 50)] = np.nan # set some random values in the first column
iris

array([[5.1, 3.5, 1.4, 0.2],
       [nan, 3. , 1.4, 0.2],
       [nan, 3.2, 1.3, 0.2],
       [nan, 3.1, 1.5, 0.2],
       [nan, 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [nan, 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [nan, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [nan, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [nan, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [nan, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [nan, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [42]:
nan_index_1 = np.where(np.isnan(iris)) # to check for nan, the official documentation always recommends using np.isnan
nan_index_1

(array([  1,   2,   3,   4,   7,  10,  12,  19,  21,  30,  35,  36,  39,
         40,  42,  46,  52,  54,  59,  62,  65,  71,  76,  91,  95,  98,
         99, 100, 101, 102, 105, 107, 108, 109, 121, 124, 126, 128, 131,
        135, 137, 138, 140, 144, 146]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0]))

In [43]:
iris[nan_index_1]
print("Number of missing values: \n", np.isnan(iris[:, 0]).sum())

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan])

Number of missing values: 
 45


In [44]:
np.isnan(iris[:, 0])

array([False,  True,  True,  True,  True, False, False,  True, False,
       False,  True, False,  True, False, False, False, False, False,
       False,  True, False,  True, False, False, False, False, False,
       False, False, False,  True, False, False, False, False,  True,
        True, False, False,  True,  True, False,  True, False, False,
       False,  True, False, False, False, False, False,  True, False,
        True, False, False, False, False,  True, False, False,  True,
       False, False,  True, False, False, False, False, False,  True,
       False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True, False, False, False,  True, False, False,  True,
        True,  True,  True,  True, False, False,  True, False,  True,
        True,  True, False, False, False, False, False, False, False,
       False, False, False, False,  True, False, False,  True, False,
        True, False,

In [45]:
nan_index_1[0]

array([  1,   2,   3,   4,   7,  10,  12,  19,  21,  30,  35,  36,  39,
        40,  42,  46,  52,  54,  59,  62,  65,  71,  76,  91,  95,  98,
        99, 100, 101, 102, 105, 107, 108, 109, 121, 124, 126, 128, 131,
       135, 137, 138, 140, 144, 146])

In [46]:
pd.DataFrame(iris).iloc[nan_index_1[0]].head(10)

0    1    2    3
1  NaN  3.0  1.4  0.2
2  NaN  3.2  1.3  0.2
3  NaN  3.1  1.5  0.2
4  NaN  3.6  1.4  0.2
7  NaN  3.4  1.5  0.2
10 NaN  3.7  1.5  0.2
12 NaN  3.0  1.4  0.1
19 NaN  3.8  1.5  0.3
21 NaN  3.7  1.5  0.4
30 NaN  3.1  1.6  0.2

## 34. How to filter a numpy array based on two or more conditions?

In [47]:
# Q. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 
# and sepallength (1st column) < 5.0

# Solution
iris = np.genfromtxt('iris_new.csv', delimiter=',', skip_header=1, usecols = [1, 2, 3, 4])
reduce_array = iris[(iris[:,3] > 1.5) & (iris[:,1] < 5)]

iris.shape

(150, 4)

In [48]:
reduce_array.shape

(52, 4)

In [49]:
reduce_array

array([[6.3, 3.3, 4.7, 1.6],
       [5.9, 3.2, 4.8, 1.8],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.7, 5.1, 1.6],
       [6. , 3.4, 4.5, 1.6],
       [6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [4.9, 2.5, 4.5, 1.7],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [7.2, 3.2, 6. , 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [7.4, 2

In [50]:
# Another solution
print("Using criteria saved as objects")

cond1 = iris[:,3] > 1.5
cond2 = iris[:,1] < 5

reduce_array2 = iris[cond1 & cond2]
reduce_array2.shape
reduce_array2

Using criteria saved as objects


(52, 4)

array([[6.3, 3.3, 4.7, 1.6],
       [5.9, 3.2, 4.8, 1.8],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.7, 5.1, 1.6],
       [6. , 3.4, 4.5, 1.6],
       [6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [4.9, 2.5, 4.5, 1.7],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [7.2, 3.2, 6. , 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [7.4, 2

In [51]:
# Another solution using reduce
print("Using reduce")
from functools import reduce

criteria = reduce(lambda x, y: x & y, (cond1, cond2))
criteria

Using reduce


array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True, False,
       False, False, False, False, False,  True, False, False, False,
       False, False,  True, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,

In [52]:
iris[criteria].shape

(52, 4)

In [53]:
iris[criteria]

array([[6.3, 3.3, 4.7, 1.6],
       [5.9, 3.2, 4.8, 1.8],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.7, 5.1, 1.6],
       [6. , 3.4, 4.5, 1.6],
       [6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [4.9, 2.5, 4.5, 1.7],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [7.2, 3.2, 6. , 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [7.4, 2

## 35. How to drop rows that contain a missing value from a numpy array?

In [54]:
# Q. Select the rows of iris_2d that does not have any nan value.

# set original print statements
np.set_printoptions(edgeitems=3,infstr='inf', linewidth=75, nanstr='nan', precision=8, suppress=False, 
                    threshold=1000, formatter=None)

In [55]:
# Solution
# Importing the titanic df
def import_titanic():
    with open("train.csv", "r") as f:
        data = f.read()
        l = []
        for row in data.split("\n")[1:-1]:
            r_ = row.split(",")
            l_ = []
            for c in r_:
                if c == "": 
                    l_.append(np.nan)
                else:
                    try:
                        l_.append(float(c))
                    except:
                        l_.append(c)
            l.append(l_)
    return l

l = import_titanic()
# only numeric columns
a = np.array(l, dtype = object)[:,[1, 2, 6, 7, 8, 10]]
# convert to float
arr = np.array(a, dtype = float)
# select rows with nan values
nan_r = np.array([~np.any(np.isnan(row)) for row in arr])
# filter the array
arr_no_nan = arr[nan_r]
arr_no_nan
# check: the sum of nans must be zero
np.isnan(arr_no_nan).sum()

array([[ 0.    ,  3.    , 22.    ,  1.    ,  0.    ,  7.25  ],
       [ 1.    ,  1.    , 38.    ,  1.    ,  0.    , 71.2833],
       [ 1.    ,  3.    , 26.    ,  0.    ,  0.    ,  7.925 ],
       ...,
       [ 1.    ,  1.    , 19.    ,  0.    ,  0.    , 30.    ],
       [ 1.    ,  1.    , 26.    ,  0.    ,  0.    , 30.    ],
       [ 0.    ,  3.    , 32.    ,  0.    ,  0.    ,  7.75  ]])

0

In [56]:
# Solution 2
print("Solution from the website")

l = import_titanic()
a = np.array(l, dtype = object)[:,[1, 2, 6, 7, 8, 10]]
arr = np.array(a, dtype = float)

Solution from the website


In [57]:
l[0:2]

[[1.0,
  0.0,
  3.0,
  '"Braund',
  ' Mr. Owen Harris"',
  'male',
  22.0,
  1.0,
  0.0,
  'A/5 21171',
  7.25,
  nan,
  'S'],
 [2.0,
  1.0,
  1.0,
  '"Cumings',
  ' Mrs. John Bradley (Florence Briggs Thayer)"',
  'female',
  38.0,
  1.0,
  0.0,
  'PC 17599',
  71.2833,
  'C85',
  'C']]

In [58]:
a

array([[0.0, 3.0, 22.0, 1.0, 0.0, 7.25],
       [1.0, 1.0, 38.0, 1.0, 0.0, 71.2833],
       [1.0, 3.0, 26.0, 0.0, 0.0, 7.925],
       ...,
       [0.0, 3.0, nan, 1.0, 2.0, 23.45],
       [1.0, 1.0, 26.0, 0.0, 0.0, 30.0],
       [0.0, 3.0, 32.0, 0.0, 0.0, 7.75]], dtype=object)

In [59]:
arr

array([[ 0.    ,  3.    , 22.    ,  1.    ,  0.    ,  7.25  ],
       [ 1.    ,  1.    , 38.    ,  1.    ,  0.    , 71.2833],
       [ 1.    ,  3.    , 26.    ,  0.    ,  0.    ,  7.925 ],
       ...,
       [ 0.    ,  3.    ,     nan,  1.    ,  2.    , 23.45  ],
       [ 1.    ,  1.    , 26.    ,  0.    ,  0.    , 30.    ],
       [ 0.    ,  3.    , 32.    ,  0.    ,  0.    ,  7.75  ]])

In [60]:
arr[np.sum(np.isnan(arr), axis = 1) == 0] # much more elegant solution

array([[ 0.    ,  3.    , 22.    ,  1.    ,  0.    ,  7.25  ],
       [ 1.    ,  1.    , 38.    ,  1.    ,  0.    , 71.2833],
       [ 1.    ,  3.    , 26.    ,  0.    ,  0.    ,  7.925 ],
       ...,
       [ 1.    ,  1.    , 19.    ,  0.    ,  0.    , 30.    ],
       [ 1.    ,  1.    , 26.    ,  0.    ,  0.    , 30.    ],
       [ 0.    ,  3.    , 32.    ,  0.    ,  0.    ,  7.75  ]])

In [61]:
np.isnan(arr[np.sum(np.isnan(arr), axis = 1) == 0]).sum()

0

## 36. How to find the correlation between two columns of a numpy array?

In [62]:
# Q. Find the correlation between SepalLength(1st column) and PetalLength(3rd column) in iris_2d

# Solution
iris = np.genfromtxt('iris_new.csv', delimiter=',', skip_header=1, usecols = [1, 2, 3, 4])

# This function computes the correlation as generally defined in signal processing texts: c_{av}[k] = sum_n a[n+k] * conj(v[n])
np.correlate(iris[:,1], iris[:,3])

array([531.89])

In [63]:
np.corrcoef(iris[:,1], iris[:,3]) # Pearson correlation

array([[ 1.        , -0.36612593],
       [-0.36612593,  1.        ]])

In [64]:
# Solution from the website
print("Solution from the website using scipy")
from scipy.stats.stats import pearsonr

corr, p_value = pearsonr(iris[:, 1], iris[:, 3])
print(corr)
print(p_value)

Solution from the website using scipy
-0.3661259325364391
4.0732285132461925e-06


## 37. How to find if a given array has any null values?

In [65]:
# Q. Find out if iris_2d has any missing values.

# Solution
iris = np.genfromtxt("iris_new.csv", delimiter=",",  dtype='float', usecols=[1,2,3,4], skip_header=1)
iris[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan # inser some null values
# 행 열에 20개씩 랜덤으로 짝을 지은 곳에 nan 배정

# first returns True second the total of nan values
f"It's {np.any(np.isnan(iris))} that we have nan values. The total amount of nan values is {np.isnan(iris).sum()}"
# print("It's {} that we have nan values. The total amout of nan values is {}".format(np.any(np.isnan(iris)), np.isnan(iris).sum())) 

"It's True that we have nan values. The total amount of nan values is 19"

In [66]:
np.isnan(iris)[0:4]

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [67]:
np.isnan(iris).any()
np.any(np.isnan(iris))

np.isnan(iris).sum()

True

True

19

## 38. How to replace all missing values with 0 in a numpy array?

In [68]:
# Q. Replace all ccurrences of nan with 0 in numpy array

# Solution
iris = np.genfromtxt("iris_new.csv", delimiter=",", dtype = "float", usecols = [1,2,3,4], skip_header=1)
iris[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan # insert some null values

In [69]:
print("Before applying nan_to_num")
np.isnan(iris).sum()

a = np.nan_to_num(iris,0) # nan -> 0

print("After applying nan_to_num")
np.isnan(a).sum()

Before applying nan_to_num


20

After applying nan_to_num


0

In [70]:
# Solution from the website
print("Solution from the website")
iris = np.genfromtxt("iris_new.csv", delimiter=",",  dtype='float', usecols=[1,2,3,4], skip_header=1)
iris[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan # insert some null values

np.isnan(iris).sum()

Solution from the website


19

In [71]:
iris[np.isnan(iris)] = 0
np.isnan(a).sum()

0

## 39. How to find the count of unique values in a numpy array?

In [72]:
# Q. Find the unique values and the count of unique values in iris's species

# Solution
print("Solution using list comprehension")

iris = np.genfromtxt("iris_new.csv", delimiter = ",", usecols=[5], dtype=object, skip_header=1)
l = [(v, np.count_nonzero(iris[iris == v])) for v in np.unique(iris)]
l

Solution using list comprehension


[(b'setosa', 50), (b'versicolor', 50), (b'virginica', 50)]

In [73]:
iris

array([b'setosa', b'setosa', b'setosa', b'setosa', b'setosa', b'setosa',
       b'setosa', b'setosa', b'setosa', b'setosa', b'setosa', b'setosa',
       b'setosa', b'setosa', b'setosa', b'setosa', b'setosa', b'setosa',
       b'setosa', b'setosa', b'setosa', b'setosa', b'setosa', b'setosa',
       b'setosa', b'setosa', b'setosa', b'setosa', b'setosa', b'setosa',
       b'setosa', b'setosa', b'setosa', b'setosa', b'setosa', b'setosa',
       b'setosa', b'setosa', b'setosa', b'setosa', b'setosa', b'setosa',
       b'setosa', b'setosa', b'setosa', b'setosa', b'setosa', b'setosa',
       b'setosa', b'setosa', b'versicolor', b'versicolor', b'versicolor',
       b'versicolor', b'versicolor', b'versicolor', b'versicolor',
       b'versicolor', b'versicolor', b'versicolor', b'versicolor',
       b'versicolor', b'versicolor', b'versicolor', b'versicolor',
       b'versicolor', b'versicolor', b'versicolor', b'versicolor',
       b'versicolor', b'versicolor', b'versicolor', b'versicolor',
       

In [74]:
np.unique(iris)

array([b'setosa', b'versicolor', b'virginica'], dtype=object)

In [75]:
[v for v in np.unique(iris)]

[b'setosa', b'versicolor', b'virginica']

In [76]:
[np.count_nonzero(iris[iris==v]) for v in np.unique(iris)]

[50, 50, 50]

## 40. How to convert a numeric to a categorical (text) array?  

https://rfriend.tistory.com/tag/np.digitize%28bins%29

In [77]:
# Q. Bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
# Less than 3 --> 'small'
# 3-5 --> 'medium'
# '>=5 --> 'large'


# Solution
iris = np.genfromtxt('iris_new.csv', delimiter = ',', 
                     usecols = [3], dtype=float, skip_header = 1)
iris

array([1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, 1.5, 1.5, 1.6, 1.4,
       1.1, 1.2, 1.5, 1.3, 1.4, 1.7, 1.5, 1.7, 1.5, 1. , 1.7, 1.9, 1.6,
       1.6, 1.5, 1.4, 1.6, 1.6, 1.5, 1.5, 1.4, 1.5, 1.2, 1.3, 1.4, 1.3,
       1.5, 1.3, 1.3, 1.3, 1.6, 1.9, 1.4, 1.6, 1.4, 1.5, 1.4, 4.7, 4.5,
       4.9, 4. , 4.6, 4.5, 4.7, 3.3, 4.6, 3.9, 3.5, 4.2, 4. , 4.7, 3.6,
       4.4, 4.5, 4.1, 4.5, 3.9, 4.8, 4. , 4.9, 4.7, 4.3, 4.4, 4.8, 5. ,
       4.5, 3.5, 3.8, 3.7, 3.9, 5.1, 4.5, 4.5, 4.7, 4.4, 4.1, 4. , 4.4,
       4.6, 4. , 3.3, 4.2, 4.2, 4.2, 4.3, 3. , 4.1, 6. , 5.1, 5.9, 5.6,
       5.8, 6.6, 4.5, 6.3, 5.8, 6.1, 5.1, 5.3, 5.5, 5. , 5.1, 5.3, 5.5,
       6.7, 6.9, 5. , 5.7, 4.9, 6.7, 4.9, 5.7, 6. , 4.8, 4.9, 5.6, 5.8,
       6.1, 6.4, 5.6, 5.1, 5.6, 6.1, 5.6, 5.5, 4.8, 5.4, 5.6, 5.1, 5.1,
       5.9, 5.7, 5.2, 5. , 5.2, 5.4, 5.1])

In [78]:
iris.astype('float')

array([1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, 1.5, 1.5, 1.6, 1.4,
       1.1, 1.2, 1.5, 1.3, 1.4, 1.7, 1.5, 1.7, 1.5, 1. , 1.7, 1.9, 1.6,
       1.6, 1.5, 1.4, 1.6, 1.6, 1.5, 1.5, 1.4, 1.5, 1.2, 1.3, 1.4, 1.3,
       1.5, 1.3, 1.3, 1.3, 1.6, 1.9, 1.4, 1.6, 1.4, 1.5, 1.4, 4.7, 4.5,
       4.9, 4. , 4.6, 4.5, 4.7, 3.3, 4.6, 3.9, 3.5, 4.2, 4. , 4.7, 3.6,
       4.4, 4.5, 4.1, 4.5, 3.9, 4.8, 4. , 4.9, 4.7, 4.3, 4.4, 4.8, 5. ,
       4.5, 3.5, 3.8, 3.7, 3.9, 5.1, 4.5, 4.5, 4.7, 4.4, 4.1, 4. , 4.4,
       4.6, 4. , 3.3, 4.2, 4.2, 4.2, 4.3, 3. , 4.1, 6. , 5.1, 5.9, 5.6,
       5.8, 6.6, 4.5, 6.3, 5.8, 6.1, 5.1, 5.3, 5.5, 5. , 5.1, 5.3, 5.5,
       6.7, 6.9, 5. , 5.7, 4.9, 6.7, 4.9, 5.7, 6. , 4.8, 4.9, 5.6, 5.8,
       6.1, 6.4, 5.6, 5.1, 5.6, 6.1, 5.6, 5.5, 4.8, 5.4, 5.6, 5.1, 5.1,
       5.9, 5.7, 5.2, 5. , 5.2, 5.4, 5.1])

In [79]:
bin = np.digitize(iris.astype('float'), [0,3,5,10]) # 0~3 : 1, 3~5 : 2, 5~10 : 3 으로 구간화
bin

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 2, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 2, 3, 3, 2, 2, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

## 41. How to create a new column from existing columns of a numpy array?  

np.newaxis : https://azanewta.tistory.com/3  



In [80]:
# Q. Create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3

# Solution
iris = np.genfromtxt("iris_new.csv", delimiter = ",", 
                     usecols=[2, 3], dtype=float, skip_header=1)

iris[0:6]

array([[3.5, 1.4],
       [3. , 1.4],
       [3.2, 1.3],
       [3.1, 1.5],
       [3.6, 1.4],
       [3.9, 1.7]])

In [81]:
iris.shape

(150, 2)

In [82]:
iris = np.c_[iris, (np.array(iris[:,0] * 3.14 * (iris[:,1])**2))/3] # creat third column
iris.shape

(150, 3)

In [83]:
iris[:5]

array([[3.5       , 1.4       , 7.18013333],
       [3.        , 1.4       , 6.1544    ],
       [3.2       , 1.3       , 5.66037333],
       [3.1       , 1.5       , 7.3005    ],
       [3.6       , 1.4       , 7.38528   ]])

In [84]:
# Solution from the website
print("Solution from website")
iris = np.genfromtxt("iris_new.csv", delimiter = ",", usecols=[2, 3], dtype=float, skip_header=1)

s = iris[:, 1] # second col
p = iris[:, 0] # first col

volume = (np.pi * p * (s**2))/3 # third col candidates

# Introduce new dimension to match iris_2d's
volume = volume[:, np.newaxis]

# Add the new column
out = np.hstack([iris, volume]) # hori

# View
out[:4]

Solution from website


array([[3.5       , 1.4       , 7.1837752 ],
       [3.        , 1.4       , 6.1575216 ],
       [3.2       , 1.3       , 5.66324436],
       [3.1       , 1.5       , 7.30420292]])

In [85]:
volume = (np.pi * p * (s**2))/3
volume[:,np.newaxis]

array([[  7.1837752 ],
       [  6.1575216 ],
       [  5.66324436],
       [  7.30420292],
       [  7.38902592],
       [ 11.8029636 ],
       [  6.97852448],
       [  8.01106127],
       [  5.95227088],
       [  7.30420292],
       [  8.71791961],
       [  9.11480749],
       [  6.1575216 ],
       [  3.80132711],
       [  6.03185789],
       [ 10.36725576],
       [  6.90207906],
       [  7.1837752 ],
       [ 11.50032351],
       [  8.95353906],
       [ 10.28976314],
       [  8.71791961],
       [  3.76991118],
       [  9.98712305],
       [ 12.85330274],
       [  8.04247719],
       [  9.11480749],
       [  8.24668072],
       [  6.97852448],
       [  8.57864234],
       [  8.31055977],
       [  8.01106127],
       [  9.66039741],
       [  8.62053024],
       [  7.30420292],
       [  4.82548632],
       [  6.19417352],
       [  7.38902592],
       [  5.30929158],
       [  8.01106127],
       [  6.19417352],
       [  4.07045688],
       [  5.66324436],
       [  9

In [86]:
iris = np.genfromtxt("iris_new.csv", delimiter = ",", usecols=[2, 3], dtype=float, skip_header=1)
s = iris[:, 1] # second col
p = iris[:, 0] # first col
volume = (np.pi * p * (s**2))/3
volume = volume[:,np.newaxis]

In [87]:
np.c_[iris, volume]

array([[  3.5       ,   1.4       ,   7.1837752 ],
       [  3.        ,   1.4       ,   6.1575216 ],
       [  3.2       ,   1.3       ,   5.66324436],
       [  3.1       ,   1.5       ,   7.30420292],
       [  3.6       ,   1.4       ,   7.38902592],
       [  3.9       ,   1.7       ,  11.8029636 ],
       [  3.4       ,   1.4       ,   6.97852448],
       [  3.4       ,   1.5       ,   8.01106127],
       [  2.9       ,   1.4       ,   5.95227088],
       [  3.1       ,   1.5       ,   7.30420292],
       [  3.7       ,   1.5       ,   8.71791961],
       [  3.4       ,   1.6       ,   9.11480749],
       [  3.        ,   1.4       ,   6.1575216 ],
       [  3.        ,   1.1       ,   3.80132711],
       [  4.        ,   1.2       ,   6.03185789],
       [  4.4       ,   1.5       ,  10.36725576],
       [  3.9       ,   1.3       ,   6.90207906],
       [  3.5       ,   1.4       ,   7.1837752 ],
       [  3.8       ,   1.7       ,  11.50032351],
       [  3.8       ,   1.5    

## 42. How to do probabilistic sampling in numpy?  

https://wikidocs.net/14597

In [88]:
# Q. Randomly sample iris's species such that setose is twice the number of versicolor and virginica

# Solution from the website
print("Solution from the website")
iris = np.genfromtxt("iris_new.csv", delimiter = ",", dtype=object, skip_header=1)

# Get the species column
species = iris[:, 5]

species

Solution from the website


array([b'setosa', b'setosa', b'setosa', b'setosa', b'setosa', b'setosa',
       b'setosa', b'setosa', b'setosa', b'setosa', b'setosa', b'setosa',
       b'setosa', b'setosa', b'setosa', b'setosa', b'setosa', b'setosa',
       b'setosa', b'setosa', b'setosa', b'setosa', b'setosa', b'setosa',
       b'setosa', b'setosa', b'setosa', b'setosa', b'setosa', b'setosa',
       b'setosa', b'setosa', b'setosa', b'setosa', b'setosa', b'setosa',
       b'setosa', b'setosa', b'setosa', b'setosa', b'setosa', b'setosa',
       b'setosa', b'setosa', b'setosa', b'setosa', b'setosa', b'setosa',
       b'setosa', b'setosa', b'versicolor', b'versicolor', b'versicolor',
       b'versicolor', b'versicolor', b'versicolor', b'versicolor',
       b'versicolor', b'versicolor', b'versicolor', b'versicolor',
       b'versicolor', b'versicolor', b'versicolor', b'versicolor',
       b'versicolor', b'versicolor', b'versicolor', b'versicolor',
       b'versicolor', b'versicolor', b'versicolor', b'versicolor',
       

In [89]:
# Approach 1 : Generate Probabilistically
np.random.seed(100)

a = np.array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'])
species_out = np.random.choice(a, 150, p=[0.5,0.25,0.25]) # a를 150개 0.5 0.25 0.25확률로 선택
species_out

print(np.unique(species_out, return_counts=True))

array(['Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-versicolor', 'Iris-virginica', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-virginica', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-setosa', 'Iris-versic

(array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype='<U15'), array([77, 37, 36]))


In [90]:
# Approach 2 : Probabilistic sampling (preferred)
np.random.seed(100)

probs = np.r_[np.linspace(0, 0.500, num=50), np.linspace(0.501, 0.750, num=50), np.linspace(0.751, 1.0, num=50)]
index = np.searchsorted(probs, np.random.random(150)) # 이진탐색
species_out = species[index]

print(np.unique(species_out, return_counts=True))

(array([b'setosa', b'versicolor', b'virginica'], dtype=object), array([77, 37, 36]))


np.random.random(150)개 각각이 그 구간안에 들어가는 index로 만들어져 나오게 된다.

## 43. How to get the second largest value of an array when grouped by another array?

In [91]:
# Q. What is the value of second longest petallength of species setosa

# Solution
header = np.genfromtxt('iris_new.csv', delimiter=',', dtype=object, skip_header=0)
header[0]

array([b'', b'sepal length (cm)', b'sepal width (cm)',
       b'petal length (cm)', b'petal width (cm)', b'target'], dtype=object)

In [92]:
iris = np.genfromtxt('iris_new.csv', delimiter=',', dtype=object, skip_header=1)

# iris
sorted_iris = iris[iris[:,5]== b'setosa'][:,3] # setosa인 것 중, 4번째 컬럼 가져옴
sorted_iris

array([b'1.4', b'1.4', b'1.3', b'1.5', b'1.4', b'1.7', b'1.4', b'1.5',
       b'1.4', b'1.5', b'1.5', b'1.6', b'1.4', b'1.1', b'1.2', b'1.5',
       b'1.3', b'1.4', b'1.7', b'1.5', b'1.7', b'1.5', b'1.0', b'1.7',
       b'1.9', b'1.6', b'1.6', b'1.5', b'1.4', b'1.6', b'1.6', b'1.5',
       b'1.5', b'1.4', b'1.5', b'1.2', b'1.3', b'1.4', b'1.3', b'1.5',
       b'1.3', b'1.3', b'1.3', b'1.6', b'1.9', b'1.4', b'1.6', b'1.4',
       b'1.5', b'1.4'], dtype=object)

In [93]:
sorted_iris = sorted_iris.astype(float)
sorted_iris

array([1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, 1.5, 1.5, 1.6, 1.4,
       1.1, 1.2, 1.5, 1.3, 1.4, 1.7, 1.5, 1.7, 1.5, 1. , 1.7, 1.9, 1.6,
       1.6, 1.5, 1.4, 1.6, 1.6, 1.5, 1.5, 1.4, 1.5, 1.2, 1.3, 1.4, 1.3,
       1.5, 1.3, 1.3, 1.3, 1.6, 1.9, 1.4, 1.6, 1.4, 1.5, 1.4])

In [94]:
sorted_iris = np.unique(sorted_iris)
sorted_iris

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.9])

In [95]:
sorted_iris.sort()
sorted_iris[::-1]

array([1.9, 1.7, 1.6, 1.5, 1.4, 1.3, 1.2, 1.1, 1. ])

In [96]:
sorted_iris[::-1][1] # the second greatest

1.7

In [97]:
# Solution from the website
iris = np.genfromtxt("iris_new.csv", delimiter = ",", dtype=object, skip_header=1)

petal_len_setosa = iris[iris[:, 5] == b'setosa', [3]].astype('float')
petal_len_setosa

array([1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, 1.5, 1.5, 1.6, 1.4,
       1.1, 1.2, 1.5, 1.3, 1.4, 1.7, 1.5, 1.7, 1.5, 1. , 1.7, 1.9, 1.6,
       1.6, 1.5, 1.4, 1.6, 1.6, 1.5, 1.5, 1.4, 1.5, 1.2, 1.3, 1.4, 1.3,
       1.5, 1.3, 1.3, 1.3, 1.6, 1.9, 1.4, 1.6, 1.4, 1.5, 1.4])

In [98]:
np.sort(petal_len_setosa)

array([1. , 1.1, 1.2, 1.2, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 1.4, 1.4,
       1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.5, 1.5,
       1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.6, 1.6,
       1.6, 1.6, 1.6, 1.6, 1.6, 1.7, 1.7, 1.7, 1.7, 1.9, 1.9])

In [99]:
np.unique(np.sort(petal_len_setosa))

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.9])

In [100]:
np.unique(np.sort(petal_len_setosa))[-2] # 뒤에서 두번째

1.7

## 44. How to sort a 2D array by a column

In [101]:
# Q. Sort the iris dataset based on sepallength column.

# Solution
headers = np.genfromtxt("iris_new.csv", delimiter = ",", dtype=object, skip_header=0)
print(list(headers[0]))
iris = np.genfromtxt("iris_new.csv", delimiter = ",", usecols=[0,1,2,3,4], skip_header=1)
iris[iris[:,1].argsort()][:5]

# Solution from the website
print(iris[iris[:,1].argsort()][:5]) # same solution

[b'', b'sepal length (cm)', b'sepal width (cm)', b'petal length (cm)', b'petal width (cm)', b'target']


array([[13. ,  4.3,  3. ,  1.1,  0.1],
       [42. ,  4.4,  3.2,  1.3,  0.2],
       [38. ,  4.4,  3. ,  1.3,  0.2],
       [ 8. ,  4.4,  2.9,  1.4,  0.2],
       [41. ,  4.5,  2.3,  1.3,  0.3]])

[[13.   4.3  3.   1.1  0.1]
 [42.   4.4  3.2  1.3  0.2]
 [38.   4.4  3.   1.3  0.2]
 [ 8.   4.4  2.9  1.4  0.2]
 [41.   4.5  2.3  1.3  0.3]]


In [102]:
iris[:,1].argsort() # a.argsort()는 어레이 a를 정렬하는 인덱스의 어레이를 반환

array([ 13,  42,  38,   8,  41,  22,   3,   6,  47,   2,  29,  12,  45,
        24,  11,  30,  57, 106,  34,   9,  37,   1,  40,  26,  49,  35,
        43,  60,   7,  93,   4,  25,  44,  46,  98,   0,  39,  17,  23,
        21,  19,  32,  28,  27,  59,  48,  84,   5,  20,  31,  10,  16,
        36,  90,  33,  53,  81,  80,  89,  88, 121,  66,  69,  94,  64,
        79,  96,  99,  15,  55, 113,  18,  95,  67,  14,  92, 114, 142,
        82, 101, 149,  61,  70,  78,  83, 138,  85,  62, 119, 127, 134,
        71,  63,  73,  91,  68,  97, 148, 126,  72, 123, 146,  56, 133,
       100,  87, 136, 103, 132, 128, 137,  51, 115,  74, 111, 104, 116,
       147,  54, 110,  58,  75,  86, 140, 108,  77,  65, 144, 145, 124,
       143,  76, 112, 139, 141,  52, 120,  50, 102, 129, 125, 109, 107,
       130, 105, 122, 118, 117, 135, 131])

## 45. How to find the most frequent value in a numpy array?  

https://blog.naver.com/timtaeil/221426580068

In [104]:
# Q. Find the most frequent value of petal length (3rd column) in iris dataset.

# Solution
np.set_printoptions(edgeitems=3,infstr='inf', linewidth=75, nanstr='nan', precision=3, 
                    suppress=False, threshold=1000, formatter=None)


headers = np.genfromtxt("iris_new.csv", delimiter = ",", dtype=object, skip_header=0)
print(list(headers[0]))

[b'', b'sepal length (cm)', b'sepal width (cm)', b'petal length (cm)', b'petal width (cm)', b'target']


In [106]:
iris = np.genfromtxt("iris_new.csv", delimiter = ",", usecols=[4], skip_header=1)
counts = np.unique([v for v in iris], return_counts=True) # we have a tuple of arrays

counts

(array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6,
        1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5]),
 array([ 5, 29,  7,  7,  1,  1,  7,  3,  5, 13,  8, 12,  4,  2, 12,  5,  6,
         6,  3,  8,  3,  3]))

In [120]:
 # extract the values and counts, zip them and sort by the counts
 # sorted : output result will be list type.
 # lambda x : x[1] <- sort by counts[1]
sort_list = sorted(list(zip(counts[0], counts[1])), key = lambda x: x[1]) 
sort_list

[(0.5, 1),
 (0.6, 1),
 (1.7, 2),
 (1.1, 3),
 (2.2, 3),
 (2.4, 3),
 (2.5, 3),
 (1.6, 4),
 (0.1, 5),
 (1.2, 5),
 (1.9, 5),
 (2.0, 6),
 (2.1, 6),
 (0.3, 7),
 (0.4, 7),
 (1.0, 7),
 (1.4, 8),
 (2.3, 8),
 (1.5, 12),
 (1.8, 12),
 (1.3, 13),
 (0.2, 29)]

In [116]:
list(zip(counts[0], counts[1]))

[(0.1, 5),
 (0.2, 29),
 (0.3, 7),
 (0.4, 7),
 (0.5, 1),
 (0.6, 1),
 (1.0, 7),
 (1.1, 3),
 (1.2, 5),
 (1.3, 13),
 (1.4, 8),
 (1.5, 12),
 (1.6, 4),
 (1.7, 2),
 (1.8, 12),
 (1.9, 5),
 (2.0, 6),
 (2.1, 6),
 (2.2, 3),
 (2.3, 8),
 (2.4, 3),
 (2.5, 3)]

In [122]:
sorted(list(zip(counts[0], counts[1])), key = lambda x: -x[0]) 

[(2.5, 3),
 (2.4, 3),
 (2.3, 8),
 (2.2, 3),
 (2.1, 6),
 (2.0, 6),
 (1.9, 5),
 (1.8, 12),
 (1.7, 2),
 (1.6, 4),
 (1.5, 12),
 (1.4, 8),
 (1.3, 13),
 (1.2, 5),
 (1.1, 3),
 (1.0, 7),
 (0.6, 1),
 (0.5, 1),
 (0.4, 7),
 (0.3, 7),
 (0.2, 29),
 (0.1, 5)]

In [115]:
#reverse the list and get the first (most frequent) the most frequent value of petal lenght is 0.2, 
#it has ocurred 28 times
sort_list[::-1][0] 

(0.2, 29)

## 46. How to find the position of the first occurrence of a value greater than a given value?  

https://emilkwak.github.io/numpy-argmax-argmin-argwhere  

numpy의 argmax(), argmin()을 이용해 최대, 최소 값의 위치를 손쉽게 알 수 있습니다. argwhere()를 사용하면 특정 데이터의 위치를 매우 간편히 찾을 수 있습니다.

In [124]:
# Q. Find the position of the first occurrence of a value greater than 1.0 in petalwidth 4th column of iris dataset

# Solution
iris = np.genfromtxt("iris_new.csv", delimiter = ",", usecols=[4], skip_header=1)

iris

array([0.2, 0.2, 0.2, 0.2, 0.2, 0.4, 0.3, 0.2, 0.2, 0.1, 0.2, 0.2, 0.1,
       0.1, 0.2, 0.4, 0.4, 0.3, 0.3, 0.3, 0.2, 0.4, 0.2, 0.5, 0.2, 0.2,
       0.4, 0.2, 0.2, 0.2, 0.2, 0.4, 0.1, 0.2, 0.2, 0.2, 0.2, 0.1, 0.2,
       0.2, 0.3, 0.3, 0.2, 0.6, 0.4, 0.3, 0.2, 0.2, 0.2, 0.2, 1.4, 1.5,
       1.5, 1.3, 1.5, 1.3, 1.6, 1. , 1.3, 1.4, 1. , 1.5, 1. , 1.4, 1.3,
       1.4, 1.5, 1. , 1.5, 1.1, 1.8, 1.3, 1.5, 1.2, 1.3, 1.4, 1.4, 1.7,
       1.5, 1. , 1.1, 1. , 1.2, 1.6, 1.5, 1.6, 1.5, 1.3, 1.3, 1.3, 1.2,
       1.4, 1.2, 1. , 1.3, 1.2, 1.3, 1.3, 1.1, 1.3, 2.5, 1.9, 2.1, 1.8,
       2.2, 2.1, 1.7, 1.8, 1.8, 2.5, 2. , 1.9, 2.1, 2. , 2.4, 2.3, 1.8,
       2.2, 2.3, 1.5, 2.3, 2. , 2. , 1.8, 2.1, 1.8, 1.8, 1.8, 2.1, 1.6,
       1.9, 2. , 2.2, 1.5, 1.4, 2.3, 2.4, 1.8, 1.8, 2.1, 2.4, 2.3, 1.9,
       2.3, 2.5, 2.3, 1.9, 2. , 2.3, 1.8])

In [125]:
i = np.where(iris > 1) # returns the index where this is true
i

(array([ 50,  51,  52,  53,  54,  55,  56,  58,  59,  61,  63,  64,  65,
         66,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  80,
         82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  94,  95,
         96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108,
        109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121,
        122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134,
        135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147,
        148, 149]),)

In [127]:
iris[i[0][0]] # first ocurrence is on index 50 // 첫번재 발생한 인덱스는 50이고 이에 해당하는 값은 1.4

1.4

In [131]:
i[0]

array([ 50,  51,  52,  53,  54,  55,  56,  58,  59,  61,  63,  64,  65,
        66,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  80,
        82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  94,  95,
        96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108,
       109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121,
       122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134,
       135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147,
       148, 149])

In [133]:
i[0][0] # 첫번째 array를 고르고, 그 안에서 첫번째 수

50

In [135]:
iris[:i[0][0] + 1] # indexing에서 마지막 미만이므로 1.4까지 포함하려면 1을 더해야 함 ==iris[:51] <- 50번째까지 출력

array([0.2, 0.2, 0.2, 0.2, 0.2, 0.4, 0.3, 0.2, 0.2, 0.1, 0.2, 0.2, 0.1,
       0.1, 0.2, 0.4, 0.4, 0.3, 0.3, 0.3, 0.2, 0.4, 0.2, 0.5, 0.2, 0.2,
       0.4, 0.2, 0.2, 0.2, 0.2, 0.4, 0.1, 0.2, 0.2, 0.2, 0.2, 0.1, 0.2,
       0.2, 0.3, 0.3, 0.2, 0.6, 0.4, 0.3, 0.2, 0.2, 0.2, 0.2, 1.4])

In [139]:
# Solution from the website
np.argwhere(iris.astype(float) > 1.0)[0] # same result but much faster and elegant

array([50])

## 47. How to replace all values greater than a given value to a given cutoff?

In [140]:
# Q. From the array a, replace all values greater than 30 to 30 and less than 10 to 10.

# Input
np.random.seed(100)
a = np.random.uniform(1,50, 20)
a

array([27.627, 14.64 , 21.801, 42.394,  1.231,  6.957, 33.867, 41.467,
        7.699, 29.18 , 44.675, 11.251, 10.081,  6.31 , 11.765, 48.953,
       40.772,  9.425, 40.995, 14.43 ])

In [143]:
# Solution
c1 = np.where(a>30)
c2 = np.where(a<10)

a[c1] = 30
a[c2] = 10

a

array([27.627, 14.64 , 21.801, 30.   , 10.   , 10.   , 30.   , 30.   ,
       10.   , 29.18 , 30.   , 11.251, 10.081, 10.   , 11.765, 30.   ,
       30.   , 10.   , 30.   , 14.43 ])

In [146]:
# Solution from the website

# Solution 1 : using np.clip
np.random.seed(100)
a = np.random.uniform(1,50, 20)

np.clip(a, a_min=10, a_max=30) # probabily the most elegant solution 

array([27.627, 14.64 , 21.801, 30.   , 10.   , 10.   , 30.   , 30.   ,
       10.   , 29.18 , 30.   , 11.251, 10.081, 10.   , 11.765, 30.   ,
       30.   , 10.   , 30.   , 14.43 ])

In [147]:
# Solution 2 : Using np.where
np.random.seed(100)
a = np.random.uniform(1,50, 20)

print(np.where(a<10, 10, np.where(a>30,30,a))) # ifelse문이랑 비슷, a<10이면 10, 아니면 그 뒤의 것 실행

[27.627 14.64  21.801 30.    10.    10.    30.    30.    10.    29.18
 30.    11.251 10.081 10.    11.765 30.    30.    10.    30.    14.43 ]


## 48. How to get the positions of top n values from a numpy array?

In [154]:
# Q. Get the positions of top 5 maximum values in a given array a.

# Input
np.random.seed(100)
a = np.random.uniform(1,50, 20)
a

array([27.627, 14.64 , 21.801, 42.394,  1.231,  6.957, 33.867, 41.467,
        7.699, 29.18 , 44.675, 11.251, 10.081,  6.31 , 11.765, 48.953,
       40.772,  9.425, 40.995, 14.43 ])

In [169]:
# Solution

# sort the numpy array with argsort(), returns the index starting from min to max value. Index 15 has the max value
a.argsort() #넘파이 배열의 원소를 오름차순으로 정렬하는 메소드입니다. 반환값은 배열의 인덱스입니다.

array([ 4, 13,  5,  8, 17, 12, 11, 14, 19,  1,  2,  0,  9,  6, 16, 18,  7,
        3, 10, 15])

In [157]:
sorted(list(zip(a, a.argsort())), key = lambda x : x[1])

[(11.25090398374229, 0),
 (29.17957314193525, 1),
 (44.674775761300936, 2),
 (9.425109623897116, 3),
 (27.626842147757305, 4),
 (21.801361946707523, 5),
 (6.310467632748502, 6),
 (40.77247430537684, 7),
 (42.39403048367528, 8),
 (10.081082757953677, 9),
 (40.99501268756616, 10),
 (33.86670515161215, 11),
 (6.9568869183725965, 12),
 (14.640099869596012, 13),
 (41.46678500014733, 14),
 (14.42961360504326, 15),
 (11.765177138624615, 16),
 (1.2312239533576557, 17),
 (48.95256545066111, 18),
 (7.698622894562695, 19)]

In [158]:
a.argsort()[-5:] # select top 5 index

array([18,  7,  3, 10, 15])

In [159]:
a.argsort()[-5:][::-1] # a.argsort()[::-1][:5] are equivalent, reverse the top 5 indee

array([15, 10,  3,  7, 18])

In [160]:
a[a.argsort()[-5:][::-1]] # get the values

array([48.953, 44.675, 42.394, 41.467, 40.995])

In [162]:
# Solution from the website
print(a.argsort())

[ 4 13  5  8 17 12 11 14 19  1  2  0  9  6 16 18  7  3 10 15]


In [163]:
np.argpartition(-a, 5)[:5]

array([15, 10,  3,  7, 18])

In [165]:
# Below methods will get you the values.
# Method 1:
a[a.argsort()][-5:]

array([40.995, 41.467, 42.394, 44.675, 48.953])

In [166]:
# Method 2:
np.sort(a)[-5:]

array([40.995, 41.467, 42.394, 44.675, 48.953])

In [167]:
# Method 3:
np.partition(a, kth=-5)[-5:]

array([40.995, 41.467, 42.394, 44.675, 48.953])

In [168]:
# Method 4:
a[np.argpartition(-a, 5)][:5]

array([48.953, 44.675, 42.394, 41.467, 40.995])

## 49. How to compute the row wise counts of all possible values in an array?

In [170]:
# Q. Compute the counts of unique values row-wise.

# Input
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))
arr

array([[ 9,  9,  4,  8,  8,  1,  5,  3,  6,  3],
       [ 3,  3,  2,  1,  9,  5,  1, 10,  7,  3],
       [ 5,  2,  6,  4,  5,  5,  4,  8,  2,  2],
       [ 8,  8,  1,  3, 10, 10,  4,  3,  6,  9],
       [ 2,  1,  8,  7,  3,  1,  9,  3,  6,  2],
       [ 9,  2,  6,  5,  3,  9,  4,  6,  1, 10]])

In [171]:
# Output contains 10 columns representing numbers from 1 to 10. The values are the counts of the numbers in the respective rows.
# For example, Cell(0,2) has the value 2, which means, the number 3 occurs exactly 2 times in the 1st row.

# Solution
print("Solution")
from collections import Counter
rows = arr.shape[0]
lc = []

for row in range(rows): # iterate over all rows in the numpy array
    counter = Counter() # on every row, create a new Counter
    counter.update(arr[row]) # feed the Counter with the row
    lc.append(dict(counter)) # append a dict in a list: each row will have it's unique dict/counter

np.array([np.vectorize(lc[row].get)(arr[row]) for row in range(rows)]) # 행별로 각 숫자들의 갯수를 셈

Solution


array([[2, 2, 1, 2, 2, 1, 1, 2, 1, 2],
       [3, 3, 1, 2, 1, 1, 2, 1, 1, 3],
       [3, 3, 1, 2, 3, 3, 2, 1, 3, 3],
       [2, 2, 1, 2, 2, 2, 1, 2, 1, 1],
       [2, 2, 1, 1, 2, 2, 1, 2, 1, 2],
       [2, 1, 2, 1, 1, 2, 1, 2, 1, 1]])

In [172]:
# Solution from the website
print("Solution from the website (incorrect)")

def counts_of_all_values_rowwise(arr2d):
    # Unique values and its counts row wise
    num_counts_array = [np.unique(row, return_counts=True) for row in arr2d]
    # Counts of all values row wise
    return([[int(b[a==i]) if i in a else 0 for i in np.unique(arr2d)] for a, b in num_counts_array])

# it has a bug
print("The solution from the website has a bug.")
counts_of_all_values_rowwise(arr)

def counts_of_all_values_rowwise_corrected(arr2d):
    num_counts_array = [np.unique(row, return_counts=True) for row in arr2d] # same as in the previous solution
    # we have a numpy array of tuples that contain for each row the elements and their counts
    ll = [] # create an empty list of lists, we will later convert in into numpy array
    for i in range(arr2d.shape[0]): # for each row in arr rows
        l = [] # create a new list where we will be adding the mappings
        rmapper = num_counts_array[i] # rmapper = row mapper. In num_counts_array for have the same amount of tuples (elemnt - count) as rows in the arr2d
        for v in arr2d[i]: # for each value in a row
            l.append(rmapper[1][np.where(rmapper[0] == v)][0]) # append to the list the count (rmapper[1]), we are using np.where to find the index of the element
        ll.append(l) # append the list to the list of lists
    return np.array(ll) # convert the lst of list into numpy 2d array

print("The solution from the website corrected.")
counts_of_all_values_rowwise_corrected(arr)

Solution from the website (incorrect)
The solution from the website has a bug.


[[1, 0, 2, 1, 1, 1, 0, 2, 2, 0],
 [2, 1, 3, 0, 1, 0, 1, 0, 1, 1],
 [0, 3, 0, 2, 3, 1, 0, 1, 0, 0],
 [1, 0, 2, 1, 0, 1, 0, 2, 1, 2],
 [2, 2, 2, 0, 0, 1, 1, 1, 1, 0],
 [1, 1, 1, 1, 1, 2, 0, 0, 2, 1]]

The solution from the website corrected.


array([[2, 2, 1, 2, 2, 1, 1, 2, 1, 2],
       [3, 3, 1, 2, 1, 1, 2, 1, 1, 3],
       [3, 3, 1, 2, 3, 3, 2, 1, 3, 3],
       [2, 2, 1, 2, 2, 2, 1, 2, 1, 1],
       [2, 2, 1, 1, 2, 2, 1, 2, 1, 2],
       [2, 1, 2, 1, 1, 2, 1, 2, 1, 1]])

## 50. How to convert an array of arrays into a flat 1d array?

In [174]:
# Q. Convert array_of_arrays into a flat linear 1d array.

# Input
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [175]:
# Solution
print("Solution")
arr.flatten()

Solution


array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [176]:
# Solution from the website
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

In [182]:
array_of_arrays = np.array([arr1, arr2, arr3])
array_of_arrays

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


array([array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])],
      dtype=object)

In [178]:
# Solution 1
arr_2d = np.array([a for arr in array_of_arrays for a in arr]) # interesting loop comprehension
arr_2d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [179]:
arr_2d = []

for arr in array_of_arrays:
    for a in arr:
        arr_2d.append(a)

np.array(arr_2d)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [185]:
# Solution 2:
arr_2d = np.concatenate(array_of_arrays)
arr_2d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])