<a href="https://colab.research.google.com/github/koojaekwan/Kaggle_study/blob/master/Numpy_exercise1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy exercise 100  

* Refer - https://www.kaggle.com/python10pm/learn-numpy-the-hard-way-70-exercises-solutions

In [ ]:
import os
import numpy as np
import pandas as pd
from google.colab import drive

drive.mount('./MyDrive')

Drive already mounted at ./MyDrive; to attempt to forcibly remount, call drive.mount("./MyDrive", force_remount=True).


In [ ]:
os.chdir('/content/MyDrive/MyDrive')  # setwd like R
os.getcwd()   # current working directory

'/content/MyDrive/MyDrive'

In [ ]:
# Allow several prints in one cell
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# importing the core library
import numpy as np

# helper functions to list the datasets available
def print_files():
    import os
    for dirname, _, filenames in os.walk('/content/MyDrive/MyDrive'):
        for filename in filenames:
            print(os.path.join(dirname, filename))

print_files()

/content/MyDrive/MyDrive/train.csv
/content/MyDrive/MyDrive/test.csv
/content/MyDrive/MyDrive/머신러닝 도감(제이펍).gdoc
/content/MyDrive/MyDrive/srr-mave-gqc - 2020년 10월 11일.gjam
/content/MyDrive/MyDrive/trick99data.csv
/content/MyDrive/MyDrive/trick83data.csv
/content/MyDrive/MyDrive/trick78data1.csv
/content/MyDrive/MyDrive/trick78data3.csv
/content/MyDrive/MyDrive/trick78data2.csv
/content/MyDrive/MyDrive/trick58data.csv
/content/MyDrive/MyDrive/trick18data.csv.zip
/content/MyDrive/MyDrive/trick8data3.csv
/content/MyDrive/MyDrive/trick8data1.csv
/content/MyDrive/MyDrive/trick8data2.csv
/content/MyDrive/MyDrive/coding_test/group_call_HMS.csv
/content/MyDrive/MyDrive/coding_test/first.pickle
/content/MyDrive/MyDrive/coding_test/first2.pickle
/content/MyDrive/MyDrive/coding_test/first3.pickle
/content/MyDrive/MyDrive/coding_test/first4.pickle
/content/MyDrive/MyDrive/coding_test/first5.pickle
/content/MyDrive/MyDrive/coding_test/p_data.pickle
/content/MyDrive/MyDrive/coding_

## 1. Import numpy as np and see the version

In [ ]:
# Q. Import numpy as np and print the version number.

# Solution
import numpy as np
print(np.__version__)

1.19.5


## 2. How to create a 1D array?

In [ ]:
# Q. Create a 1D array of numbers from 0 to 9

# Desired Output
# > array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Solution
arr = np.arange(10)

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 3. How to create a boolean array?

In [ ]:
# Q. Create a 3×3 numpy array of all True’s

# Solution
arr = np.repeat(True, 9).reshape(3, -1)

arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
np.repeat(True, 9)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [ ]:
np.repeat(True, 9).reshape(3, 3) # the unspecified value is inferred to be 3

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
np.repeat(True, 10).reshape(2, 5)
np.repeat(True, 10).reshape(2, -1) # -1 : 2행으로 설정하고 열은 알아서 자동맞춤

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## 4. How to extract items that satisfy a given condition from 1D array?

In [ ]:
# Q. Extract all odd numbers from arr
# Input 
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Desired Output
# > array([1, 3, 5, 7, 9])

# Solution
odds = arr[arr%2 != 0]
odds

array([1, 3, 5, 7, 9])

In [ ]:
arr%2 != 0 # bool type을 조건으로 주어 홀수만 출력

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

## 5. How to replace items that satisfy a condition with another value in numpy array?

In [ ]:
# Q. Replace all odd numbers in arr with -1
# Input 
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Desired Output
# >  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

# Solution
arr[arr%2 != 0] = -1  # 홀수 자리에 -1을 대입하여 대체
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

## 6. How to replace items that satisfy a condition without affecting the original array?

In [ ]:
# Q. Replace all odd numbers in arr with -1 without changing arr
# Input 
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Desired Output
# out #>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
# arr #>  array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Solution
out = arr.copy() # 복사 / 단순히 = 로 하면 주소가 같이 참조되어 동시에 변한다.
out[out%2 != 0] = -1

out

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [ ]:
print("Modified array")
out

Modified array


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [ ]:
print("Original array")
arr

Original array


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 7. How to reshape an array?

In [ ]:
# Q. Convert a 1D array to a 2D array with 2 rows
# Input 
arr = np.arange(10)
print("Input")
arr

Input


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Desired Output
# > array([[0, 1, 2, 3, 4],
# >        [5, 6, 7, 8, 9]])

# Solution
print("Solution: reshaped array")
arr.reshape(2,-1)  # Same as 'arr.reshape(2,5)'

Solution: reshaped array


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## 8. How to stack two arrays vertically?

In [ ]:
# Q. Stack arrays a and b vertically
# Input
print("Input")
a = np.arange(10).reshape(2,-1) # np.arrange(10).reshape(2,5)
b = np.repeat(1, 10).reshape(2,-1) # np.repeat(1, 10).reshape(2,5)

a

Input


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
# Desired Output
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9],
#>        [1, 1, 1, 1, 1],
#>        [1, 1, 1, 1, 1]])

# Solution
print("Solution: verticaly stacked arrays")
np.vstack((a, b)) # vertical

Solution: verticaly stacked arrays


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## 9. How to stack two arrays horizontally?

In [ ]:
# Q. Stack the arrays a and b horizontally.
# Input
print("Input")
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

a

Input


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
# Desired Output
# > array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
# >        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

# Solution
print("Solution: horizontally stacked arrays")
np.hstack((a, b)) # horizontal

Solution: horizontally stacked arrays


array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## 10. How to generate custom sequences in numpy without hardcoding?  

https://stackoverflow.com/questions/25471878/repeating-each-element-of-a-numpy-array-5-times

In [ ]:
# Q. Create the following pattern without hardcoding. 
# Use only numpy functions and the below input array a.

# Input
print("Input")
a = np.array([1,2,3])

a

Input


array([1, 2, 3])

In [ ]:
# Desired Output
# > array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

# Solution
# using repeat to generate the 111222.. sequence and hstack 3 times the original array
solution_array = np.hstack((np.repeat(a,3),a,a,a))
solution_array

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [ ]:
# just to help us see all the array-
np.set_printoptions(threshold=len(solution_array))

solution_array

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [ ]:
np.repeat(a,3) # 각 원소를 3번씩 반복

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [ ]:
np.tile(a, 3) # 전체 array를 3번 반복

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

## 11. How to get the common items between two python numpy arrays?

In [ ]:
# Q. Get the common items between a and b

# Input
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

a

array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])

In [ ]:
b

array([ 7,  2, 10,  2,  7,  4,  9,  4,  9,  8])

In [ ]:
# Desired Output
# array([2,4])

# Solution
np.unique(a[a==b])

array([2, 4])

In [ ]:
k = np.array([2,3,5])
k2 = np.array([2,4,3])

k==k2
np.unique(k[k==k2])  # 자리 배열이 같은 원소들을 unique로 겹치지 않게 뽑아낸다.

array([ True, False, False])

array([2])

## 12. How to remove from one array those items that exist in another?

In [ ]:
# Q. From array a remove all items present in array b

# Input
a = np.arange(5) + 1 # np.array([1,2,3,4,5])
b = np.arange(5) + 5 # np.array([5,6,7,8,9])

a; b

array([1, 2, 3, 4, 5])

array([5, 6, 7, 8, 9])

In [ ]:
# Desired Output
# array([1,2,3,4])

# Solution
np.isin(a,b)
a[~np.isin(a,b)]
# np.isin to find the common elements 
#(returns an array of Booleans). To filter only False, use ~ (CTRL + ALT + 4)

array([False, False, False, False,  True])

array([1, 2, 3, 4])

## 13. How to get the positions where elements of two arrays match?

In [ ]:
# Q. Get the positions where elements of a and b match

# Input
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

a

array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])

In [ ]:
b

array([ 7,  2, 10,  2,  7,  4,  9,  4,  9,  8])

In [ ]:
# Desired Output
# > (array([1,3,5,7]),)

# Solution
np.where(a==b)
# Notice: the solution if the INDEX but the values

(array([1, 3, 5, 7]),)

In [ ]:
a[np.where(a==b)]
b[np.where(a==b)]

array([2, 2, 4, 4])

array([2, 2, 4, 4])

## 14. How to extract all numbers between a given range from a numpy array?

In [ ]:
# Q. Get all items between 5 and 10 from a.

# Input
a = np.array([2,6,1,9,10,3,27])

a

array([ 2,  6,  1,  9, 10,  3, 27])

In [ ]:
# Desired Output
# (array([6,9,10]),)

# Solution
a[(a>5) & (a<10)]

array([6, 9])

## How to make a python function that handles scalars to work on numpy arrays?

In [ ]:
# Q. Convert the function maxx that works on two scalars, to work on two arrays.

# Input

def maxx(x,y):
    """
    Get the maximum of two items
    """

    if x>=y:
        return x
    else:
        return y

print("Result of the maxx function")
maxx(1,5)

Result of the maxx function


5

In [ ]:
a = np.array([5,7,9,8,6,4,5])
b = np.array([6,3,4,8,9,7,1])

a;b

array([5, 7, 9, 8, 6, 4, 5])

array([6, 3, 4, 8, 9, 7, 1])

In [ ]:
# Desired Output
# pair_max(a,b)
# > array([6., 7.,9., 7., 5.,])

# Solution

def pair_max(a,b):
    return np.array([max(x,y) for x,y in zip(a,b)])

# using a list comprehension to find 
#the max between 2 arrays elementwise (using zip) and convert to numpy array
pair_max(a,b)

array([6, 7, 9, 8, 9, 7, 5])

In [ ]:
[max(x,y) for x,y in zip(a,b)]

[6, 7, 9, 8, 9, 7, 5]

## 16. How to swap two columns in a 2d numpy array?

In [ ]:
# Q. Swap columns 1 and 2 in the array arr.

# Input
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
# Solution
temp = arr[:,0].copy() # temporary variable
temp # 1컬럼

array([0, 3, 6])

In [ ]:
arr[:,0], arr[:,1] = arr[:,1], temp

In [ ]:
arr

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

## 17. How to swap two rows in a 2d numpy array?

In [ ]:
# Q. Swap rows 1 and 2 in the array arr:
# Input
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
# Solution
temp = arr[0,:].copy() # temporary variable
temp # 1행

array([0, 1, 2])

In [ ]:
arr[0,:], arr[1,:] = arr[1,:], temp

In [ ]:
arr

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

## 18. How to reverse the rows of a 2D array?

In [ ]:
# Q. Reverse the rows of a 2D array arr.

# Input
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
# Solution
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [ ]:
arr[::-1,:] # exactly the same

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

## 19. How to reverse the columns of a 2D array?

In [ ]:
# Q. Reverse the columns of a 2D array arr.

# Input
print("Input")
arr = np.arange(9).reshape(3,3)
arr

Input


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
# Solution
print("Solution")
arr[:, ::-1]

Solution


array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

## 20. How to create a 2D array containing random floats between 5 and 10?

In [ ]:
# Q. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.

# Solution

# randint first argument: lower bound, second argument: higher bound (if you put 10, it will max return 9, so we add 1),
# third argument: number of samples. Then we reshape and done.

np.random.randint(5, 11, 15).reshape(5,3)

array([[ 6,  7,  7],
       [ 9,  6,  6],
       [ 6, 10,  7],
       [10,  7,  8],
       [ 8,  6,  5]])

## 21. How to print only 3 decimal places in python numpy array?

In [ ]:
# Q. Print or show only 3 decimal places of the numpy array rand_arr.

# Setting print options to default
np.set_printoptions(edgeitems=3,infstr='inf', linewidth=75, nanstr='nan', precision=8,
                    suppress=False, threshold=1000, formatter=None)

In [ ]:
# Input
rand_arr = np.random.random((5,3))
rand_arr

array([[0.13693931, 0.58940219, 0.01987679],
       [0.37257596, 0.36479357, 0.85100212],
       [0.83326409, 0.43545396, 0.82360207],
       [0.11938688, 0.8467816 , 0.44010511],
       [0.18804441, 0.43812328, 0.8461141 ]])

In [ ]:
# Solution
np.set_printoptions(precision=3)
rand_arr

array([[0.137, 0.589, 0.02 ],
       [0.373, 0.365, 0.851],
       [0.833, 0.435, 0.824],
       [0.119, 0.847, 0.44 ],
       [0.188, 0.438, 0.846]])

## 22. How to pretty print a numpy array by suppressing the scientific notation (like 1e10)?  

과학적 표기를 소수점 형태로 표현

In [ ]:
# Q. Pretty print rand_arr by suppressing the scientific notation (like 1e10)

# Setting print options to default
np.set_printoptions(edgeitems=3,infstr='inf', linewidth=75, nanstr='nan', precision=8, 
                    suppress=False, threshold=1000, formatter=None)

In [ ]:
# Input
np.random.seed(100)

rand_arr = np.random.random([3,3])/1e3
rand_arr

array([[5.43404942e-04, 2.78369385e-04, 4.24517591e-04],
       [8.44776132e-04, 4.71885619e-06, 1.21569121e-04],
       [6.70749085e-04, 8.25852755e-04, 1.36706590e-04]])

In [ ]:
# Desired Output
# > array([[ 0.000543,  0.000278,  0.000425],
# >        [ 0.000845,  0.000005,  0.000122],
# >        [ 0.000671,  0.000826,  0.000137]])


# Solution
np.set_printoptions(suppress=True) # suppress : 진압하다. 금하다. 숨기다.
rand_arr

array([[0.0005434 , 0.00027837, 0.00042452],
       [0.00084478, 0.00000472, 0.00012157],
       [0.00067075, 0.00082585, 0.00013671]])

## 23. How to limit the number of items printed in output of numpy array?

In [ ]:
# Q. Limit the number of items printed in python numpy array a to a maximum of 6 elements.

# Setting print options to default
np.set_printoptions(edgeitems=3,infstr='inf', linewidth=75, nanstr='nan', precision=8,
                    suppress=False, threshold=1000, formatter=None)

In [ ]:
# Input
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
# Desired Output
# > array([0,1,2,...,12,13,14])

# Solution
np.set_printoptions(threshold=6) # 배열에서 6개까지만 출력하여 표현
a

array([ 0,  1,  2, ..., 12, 13, 14])

## 24. How to print the full numpy array without truncating

In [ ]:
# Q. Print the full numpy array a without truncating.

# Input
np.set_printoptions(threshold=6)
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14])

In [ ]:
# Desired Output
# > array([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14])

# Solution
np.set_printoptions(threshold=len(a))
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## 25. How to import a dataset with numbers and texts keeping the text intact in python numpy?

In [ ]:
# Q. Import the titanic dataset keeping the text intact.

# Input
# Use the titanic dataset provided
print("Solution")
titanic = np.genfromtxt('train.csv', delimiter=',', skip_header=1, 
                     usecols = [0, 1, 2, 3, 4, 5], dtype = None)

titanic

Solution


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:7: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  import sys


array([(  1, 0, 3, b'"Braund', b' Mr. Owen Harris"', b'male'),
       (  2, 1, 1, b'"Cumings', b' Mrs. John Bradley (Florence Briggs Thayer)"', b'female'),
       (  3, 1, 3, b'"Heikkinen', b' Miss. Laina"', b'female'), ...,
       (889, 0, 3, b'"Johnston', b' Miss. Catherine Helen ""Carrie"""', b'female'),
       (890, 1, 1, b'"Behr', b' Mr. Karl Howell"', b'male'),
       (891, 0, 3, b'"Dooley', b' Mr. Patrick"', b'male')],
      dtype=[('f0', '<i8'), ('f1', '<i8'), ('f2', '<i8'), ('f3', 'S23'), ('f4', 'S62'), ('f5', 'S6')])